#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

nicknames = {}

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def trata_nick(conexao, nickname):
    if validar_nome(nickname):
        if nickname.lower() in nicknames:
            if conexao in nicknames.values():
                nickAtual = list(nicknames.keys())[list(nicknames.values()).index(conexao)]
                conexao.enviar(b":server 433 %s %s :Nickname is already in use\r\n"  % (nickAtual ,nickname))
            else:
                conexao.enviar(b":server 433 * %s :Nickname is already in use\r\n" % nickname)
        else:
            #já possui um nick => remove o antigo, coloca um novo
            if conexao in nicknames.values():
                nickAtual = list(nicknames.keys())[list(nicknames.values()).index(conexao)]
                del nicknames[nickAtual] #deleta o nick antigo 
                nicknames[(nickname).lower().rstrip(b'\r') ] =  conexao #coloca o novo
                conexao.enviar(b":%s NICK %s\r\n" % (nickAtual,nickname))
                
            #não tem um nick => só atribui o [nick]=conexao
            else:
                nicknames[(nickname).lower().rstrip(b'\r') ] =  conexao
                conexao.enviar(b':server 001 %s :Welcome\r\n' % nickname)
                conexao.enviar(b':server 422 %s :MOTD File is missing\r\n' % nickname)
    else:
        conexao.enviar(b':server 432 * %s :Erroneous nickname\r\n' % nickname)

def priv_message(conexao, nickname, mensagem):
    remetente = list(nicknames.keys())[list(nicknames.values()).index(conexao)] #pega o nick do remetente
    
    #se o destinatario EXISTIR => se não, n faz nada
    if nickname in nicknames:
        destinario = nicknames[nickname] #conexao do destinatario
        destinario.enviar(b':' + remetente + b' PRIVMSG ' + nickname + b' :' + mensagem + b'\r\n')

def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)

    conexao.dadosResiduais += dados

    mensagens = conexao.dadosResiduais.split(b'\n')

    if(len(mensagens)>=2):
        for i in range(0,(len(mensagens) - 1)):
            if b'PING' in mensagens[i]:
                conexao.enviar(b':server PONG server :' + mensagens[i].split(b' ', 1)[1] + b'\n')
            if b'NICK' in mensagens[i]:
                trata_nick(conexao, mensagens[i].split(b' ', 1)[1].rstrip(b'\r'))
            if b'PRIVMSG' in mensagens[i]:
                priv_message(conexao, mensagens[i].split(b' ')[1].rstrip(b'\r').lower(), mensagens[i].split(b' ')[2].strip(b':\r'))
                

    if(conexao.dadosResiduais[-1] == b'\n'):
        if b'PING' in mensagens[i]:
                conexao.enviar(b':server PONG server :' + mensagens[i].split(b' ', 1)[1] + b'\n')
        if b'NICK' in mensagens[i]:
            trata_nick(conexao, mensagens[i].split(b' ')[1].rstrip(b'\r'))
        if b'PRIVMSG' in mensagens[i]:
            priv_message(conexao, mensagens[i].split(b' ')[1].rstrip(b'\r').lower(),mensagens[i].split(b' ')[2].strip(b':\r'))
    else:
        conexao.dadosResiduais = mensagens[-1]


    
    print(conexao, dados)


def conexao_aceita(conexao):
    conexao.dadosResiduais = b''
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()